get_customs_list:
  name: Custom component list download
  description: Download the custom list from repository
  fields:
    config_entry:
      name: Repository
      description: Select the remote repository to use.
      required: true
      selector:
        config_entry:
          integration: my_custom_manager
get_supported_versions:
  name: Supported version list for the custom
  description: Download all the supported version for the custom component from repository
  fields:
    config_entry:
      name: Repository
      description: Select the remote repository to use.
      required: true
      selector:
        config_entry:
          integration: my_custom_manager
    component:
      name: Remote component
      description: The remote component.
      example: my_custom
      required: true
      selector:
        text:
    show_unstable:
      name: Show unstable versions
      description: Show also the unstable versions (alpha/beta/dev/rc)
      required: false
      selector:
        boolean:
download_custom:
  name: Custom component download
  description: Download a custom componet from a remote repository.
  fields:
    config_entry:
      name: Repository
      description: Select the remote repository to use.
      required: true
      selector:
        config_entry:
          integration: my_custom_manager
    component:
      name: Remote component
      description: The remote component.
      example: my_custom
      required: true
      selector:
        text:
    version:
      name: Version
      description: Specific version to download.
      example: 1.3.2
      required: false
      selector:
        text: